Fix indentation

diff --git a/.gitea/workflows/publish-nuget.yaml b/.gitea/workflows/publish-nuget.yaml
--- a/.gitea/workflows/publish-nuget.yaml
+++ b/.gitea/workflows/publish-nuget.yaml
@@ -26,15 +26,15 @@ jobs:
 
       - name: Pack all projects
         run: |
-    	    set -e
-    	    for projfile in $(find . -name "*.csproj"); do
-      	        if grep -q "<IsPackable>true</IsPackable>" "$projfile"; then
-        	    echo "Packing $projfile..."
-        	    if ! dotnet pack "$projfile" -c Release -o ./artifacts; then
-          	    	echo "⚠️ Failed to pack $projfile"
-        	    fi
-      	    	fi
-    	    done
+          set -e
+          for projfile in $(find . -name "*.csproj"); do
+            if grep -q "<IsPackable>true</IsPackable>" "$projfile"; then
+              echo "Packing $projfile..."
+              if ! dotnet pack "$projfile" -c Release -o ./artifacts; then
+                echo "Failed to pack $projfile"
+              fi
+            fi
+          done
 
       - name: Publish all packages
         env:
